//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WSRestApiApp {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WSRestApiApp.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;protocol&quot;: &quot;EXECUTEUIACTION&quot;,
        ///  &quot;UIActionName&quot;: &quot;PickListSavePicklistInfo&quot;,
        ///  &quot;Parameters&quot;: [
        ///    {
        ///      &quot;_ClassName&quot;: &quot;TObjectParameter&quot;,
        ///      &quot;ParamName&quot;: &quot;Data&quot;,
        ///      &quot;Description&quot;: &quot;&quot;,
        ///      &quot;Required&quot;: false,
        ///      &quot;UserParam&quot;: false,
        ///      &quot;ParameterType&quot;: &quot;ptInput&quot;,
        ///      &quot;ObjectClass&quot;: &quot;TDataObj&quot;,
        ///      &quot;ParamValue&quot;: {
        ///        &quot;JobGuid&quot;: &quot;{623de598-3faf-4f07-b240-8ab198aab751}&quot;,
        ///        &quot;PickList&quot;: {
        ///          &quot;Heading&quot;: [
        ///            &quot;ITEMGUID&quot;,
        ///            &quot;ITEMNO&quot;,
        ///      [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EXECUTEUIACTION {
            get {
                return ResourceManager.GetString("EXECUTEUIACTION", resourceCulture);
            }
        }
    }
}
